trigger:
- main

pr: none

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    set -e
    npm install
    npm run build
  displayName: 'npm install and build'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'shifurunssh'
    sourceFolder: 'dist'
    contents: '**'
    targetFolder: '/home/ubuntu/docusaurus-dist'
    readyTimeout: '20000'
    cleanTargetFolder: true
    failOnEmptySource: true

- task: SSH@0
  inputs:
    sshEndpoint: 'shifurun-ssh'
    runOptions: 'inline'
    inline: |
      sudo rm -rf /var/www/docusaurus.shifu.run
      sudo mv /home/ubuntu/docusaurus-dist /var/www/docusaurus.shifu.run
    readyTimeout: '20000'